baseURL = 'https://saligrama.io/photo/'
languageCode = 'en-us'
title = "Aditya's Photos"
author = 'Aditya Saligrama'
copyright = "© 2022 Aditya Saligrama"
paginate = 5000

theme = ["newsroom", "hugo-shortcode-gallery"]

[params]
    mainSections = ["aviation", "nature", "misc"]
    locale = "en_US"
    googleAnalytics = "G-L1P68K8054"
    twitter = "@saligrama_a"
    disableDarkMode = true